# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: global_development
  pool: 5
  username: enbake
  password: admin
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: global_test
  pool: 5
  username: enbake
  password: admin
  host: localhost 

production:
  adapter: postgresql
  encoding: unicode
  database: global_development
  pool: 5
  username: enbake
  password: admin
  host: localhost
